#!/bin/bash

. /usr/share/debconf/confmodule


set -e

db_beginblock
db_input high geonode/hostname || true
db_input high geonode/django_user || true
db_input high geonode/django_password || true
db_endblock
db_go

db_get geonode/django_password
