#!/bin/sh
# post script for geonode
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove|upgrade|deconfigure)
	a2dissite geonode
	a2ensite default

	rm -rf /var/lib/geonode
	rm -rf /var/www/geonode/wsgi
	rm -rf /var/www/geonode/static
	rm -rf /var/lib/tomcat6/webapps/geoserver
	rm -rf /var/lib/tomcat6/geonetwork

	rm -rf /usr/share/geonode/role.sql
	rm -rf /usr/share/geonode/admin.json
	rm -rf /usr/share/geonode/patch*
	rm -rf /usr/bin/geonode
    ;;

    purge)
	set +e
	`su - postgres -c 'dropdb geonode'` || true
	`su - postgres -c 'dropuser geonode'` || true
	set -e
	rm -rf /var/lib/geoserver
    ;;
    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

invoke-rc.d apache2 start
invoke-rc.d tomcat6 start
#DEBHELPER#

exit 0
